- hosts: nginx
  become: true 
  tasks:
    - name: Add ssh private key
      copy: 
        src: private_key
        dest: /home/vmuser/.ssh/private_key
        mode: '0600'
    - name: Install squid
      apt:
        name: squid
        state: present
        update_cache: yes
    - name: Copy squid config
      copy:
        src: squid.conf
        dest: /etc/squid/squid.conf
        mode: '0644'
    - name: Restart squid
      systemd:
          name: squid
          state: restarted